### ISSUE TITLE
HelperExtensions.cs

### ISSUE THREAD

**Issue by eedudka** [Hilres/Hilres.Yahoo.ApiClient#1]
Good afternoon. I am trying to use this library in my program, but when I try to get data, I get the error:
 "The debugger could not find the source file"C:\Code\Hilres .Yahoo.ApiClient\Hilres.Yahoo.ApiClient\HelperExtensions.cs"."

**Comment by danh955** [comment]
I tried to duplicate the error by creating a quick console app.   I used Visual Studio IDE v17.2.5
```c#
using Hilres.Yahoo.ApiClient;
var client = new YahooClient();
var result = await client.GetPricesAsync("msft", new(2022, 1, 3), new(2022, 1, 8));
Console.WriteLine($"Successful = {result.IsSuccessful}");
Console.WriteLine($"Count = {result.Prices.Count()}");
````
But did not get any errors stepping through the code.  The "C:\Code" is the location I do my development in.  All 21 test cases still passed.  Not sure what's going on.

**Comment by danh955** [comment]
Unable to reproduce.
